/*
 * tvw-sdr, userspace driver for TVW750 devices
 * Copyright (C) 2013  Joshua Roys <roysjosh@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef TVWREG_H
#define TVWREG_H

/* register definitions more or less from linux/drivers/gpu/drm/radeon/radeon_reg.h */
#define TVW_I2C_CNTL_0				0x03e0
#define   TVW_I2C_DONE				(1 << 0)
#define   TVW_I2C_NACK				(1 << 1)
#define   TVW_I2C_HALT				(1 << 2)
#define   TVW_I2C_SOFT_RST			(1 << 5)
#define   TVW_I2C_DRIVE_EN			(1 << 6)
#define   TVW_I2C_DRIVE_SEL			(1 << 7)
#define   TVW_I2C_START				(1 << 8)
#define   TVW_I2C_STOP				(1 << 9)
#define   TVW_I2C_RECEIVE			(1 << 10)
#define   TVW_I2C_ABORT				(1 << 11)
#define   TVW_I2C_GO				(1 << 12)
#define   TVW_I2C_PRESCALE_SHIFT		16
#define TVW_I2C_CNTL_1				0x03e4
#define   TVW_I2C_DATA_COUNT_SHIFT		0
/* the definition below is likely not correct;
 * we can have data lengths larger than 4 bits can hold
 */
#define   TVW_I2C_ADDR_COUNT_SHIFT		4
#define   TVW_I2C_INTRA_BYTE_DELAY_SHIFT	8
#define   TVW_I2C_SEL				(1 << 16)
#define   TVW_I2C_EN				(1 << 17)
#define   TVW_I2C_TIME_LIMIT_SHIFT		24
#define TVW_I2C_DATA				0x03e8

/* these register definitions were discovered in a table-like struct
 * in the proprietary binary driver
 */
#define TVW_RBBM_CTRL                                   0x0000
#define TVW_RBBM_TIMER_STATUS                           0x0004
#define TVW_RBBM_BUS_TIMER                              0x0008
#define TVW_TOP_INTERRUPT_STATUS                        0x0010
#define TVW_RBBM_INTERRUPT_CLEAR                        0x0014
#define TVW_RBBM_INTERRUPT_STATUS                       0x0014
#define TVW_RBBM_INTERRUPT_MASK0                        0x0018
#define TVW_RBBM_INTERRUPT_MASK1                        0x001c
#define TVW_RBBM_INTERRUPT_MASK2                        0x0020
#define TVW_HCU_FIFOPORT_C                              0x0080
#define TVW_HCU_FIFOPORT_D                              0x0084
#define TVW_HCU_FIFOPORT_E                              0x0088
#define TVW_HCU_TEST_MEM_BASE_LO                        0x0090
#define TVW_HCU_TEST_MEM_BASE_HI                        0x0094
#define TVW_HCU_TEST_CONTROL                            0x0098
#define TVW_HCU_STATUS                                  0x009c
#define TVW_USB_EXT_CONTROL                             0x00a0
#define TVW_HCU_DEBUG_MUX                               0x00a4
#define TVW_PCIE_INDEX                                  0x00b0
#define TVW_PCIE_DATA                                   0x00b4
#define TVW_PCIE_PORT_INDEX                             0x00b8
#define TVW_PCIE_PORT_DATA                              0x00bc
#define TVW_USB_INTERRUPT_CLEAR                         0x00d0
#define TVW_USB_INTERRUPT_STATUS                        0x00d0
#define TVW_USB_INTERRUPT_MASK0                         0x00d4
#define TVW_USB_INTERRUPT_MASK1                         0x00d8
#define TVW_HOST_INTERRUPT_INFO                         0x00dc
#define TVW_USB_MEM_BASE                                0x00e0
#define TVW_USB_POWER_CONTROL                           0x00e4
#define TVW_USB_DEVICE_ID                               0x00ec
#define TVW_VOLTAGE_CONTROL0                            0x00f0
#define TVW_VOLTAGE_CONTROL1                            0x00f4
#define TVW_VOLTAGE_CONTROL2                            0x00f8
#define TVW_USB_PATCH_REG                               0x00fc
#define TVW_DVSO_VB_START                               0x0180
#define TVW_DVSO_VB_FINISH                              0x0184
#define TVW_DVSO_FLD_ID                                 0x0188
#define TVW_DVSO_VIP2_CTL                               0x0194
#define TVW_DVSO_ANC_ID                                 0x0198
#define TVW_DVSO_VIP2_CTL2                              0x019c
#define TVW_PCU_INTERRUPT_CLEAR                         0x0200
#define TVW_PCU_INTERRUPT_STATUS                        0x0200
#define TVW_PCU_INTERRUPT_MASK0                         0x0204
#define TVW_PCU_INTERRUPT_MASK2                         0x020c
#define TVW_PCU_INTERRUPT_FORCE1                        0x0218
#define TVW_GPIO_INPUT_VALUE                            0x0220
#define TVW_GPIO_OUTPUT_VALUE                           0x0224
#define TVW_GPIO_OUTPUT_ENABLE                          0x0228
#define TVW_GPIO_INTERRUPT_MODE                         0x022c
#define TVW_GPIO_INTERRUPT_POLARITY                     0x0230
#define TVW_PCU_SOFT_RESETS                             0x0240
#define TVW_PCU_STATUS                                  0x0244
#define TVW_BTLD_HEADER                                 0x0248
#define TVW_BTLD_RDADR                                  0x024c
#define TVW_BTLD_DATA                                   0x0250
#define TVW_PCU_DEBUG_REGISTER                          0x0254
#define TVW_SPIC_RDATA0                                 0x0320
#define TVW_SPIC_RDATA1                                 0x0324
#define TVW_SPIC_STATUS                                 0x0328
#define TVW_SPIC_WDATA                                  0x032c
#define TVW_SPIC_INSTR_ADDR                             0x0330
#define TVW_SPIC_PRESCALE                               0x0334
#define TVW_I2CM_CNTL_0                                 0x03e0
#define TVW_I2CM_CNTL_1                                 0x03e4
#define TVW_I2CM_DATA                                   0x03e8
#define TVW_I2CM_INTERRUPT_CLEAR                        0x03ec
#define TVW_I2CM_INTERRUPT_FORCE                        0x03f0
#define TVW_MC_INTERRUPT_CLEAR                          0x0420
#define TVW_MC_INTERRUPT_STATUS                         0x0420
#define TVW_MC_INTERRUPT_MASK0                          0x0424
#define TVW_MC_INTERRUPT_MASK2                          0x042c
#define TVW_MEM_CNTL                                    0x0460
#define TVW_SMGR_FEVIDWR_VF_CNTL0                       0x0528
#define TVW_SMGR_FEVIDWR_VF_CNTL1                       0x052c
#define TVW_SMGR_RAWVIDRD_VF_CNTL0                      0x0538
#define TVW_SMGR_RAWVIDRD_VF_CNTL1                      0x053c
#define TVW_SMGR_FEAUDWR_VF_CNTL0                       0x0544
#define TVW_SMGR_FEAUDWR_VF_CNTL1                       0x0548
#define TVW_SMGR_RAWAUDRD_VF_CNTL0                      0x0554
#define TVW_SMGR_RAWAUDRD_VF_CNTL1                      0x0558
#define TVW_SMGR_AVBS1WR_VF_CNTL0                       0x0564
#define TVW_SMGR_AVBS1WR_VF_CNTL1                       0x0568
#define TVW_SMGR_AVBS1RD_VF_CNTL0                       0x0574
#define TVW_SMGR_AVBS1RD_VF_CNTL1                       0x0578
#define TVW_SMGR_SCATGATH_VF_CNTL0                      0x0584
#define TVW_SMGR_SCATGATH_VF_CNTL1                      0x0588
#define TVW_MDSP_MIPS1_VF_CNTL0                         0x05a4
#define TVW_MDSP_MIPS1_VF_CNTL1                         0x05a8
#define TVW_PCU_VF_CNTL0                                0x05c4
#define TVW_PCU_VF_CNTL1                                0x05c8
#define TVW_HCU_VF_CNTL0                                0x05d4
#define TVW_HCU_VF_CNTL1                                0x05d8
#define TVW_SMGR_AVBS2WR_VF_CNTL0                       0x05e4
#define TVW_SMGR_AVBS2WR_VF_CNTL1                       0x05e8
#define TVW_SMGR_AVBS2RD_VF_CNTL0                       0x05f4
#define TVW_SMGR_AVBS2RD_VF_CNTL1                       0x05f8
#define TVW_SMGR_CSCRD1_VF_CNTL0                        0x0604
#define TVW_SMGR_CSCRD1_VF_CNTL1                        0x0608
#define TVW_SMGR_CSCRD2_VF_CNTL0                        0x0614
#define TVW_SMGR_CSCRD2_VF_CNTL1                        0x0618
#define TVW_DUMMY_ADDR_CNTL                             0x0630
#define TVW_DUMMY_RD_CNTL                               0x0634
#define TVW_DUMMY_WR_CNTL                               0x0638
#define TVW_DUMMY_LINE_INTERVAL                         0x0640
#define TVW_DUMMY_BLK_INTERVAL                          0x0644
#define TVW_DUMMY_VF_CNTL0                              0x0654
#define TVW_DUMMY_VF_CNTL1                              0x0658
#define TVW_DUMMY_WRITE_DATA_0L                         0x0660
#define TVW_DUMMY_WRITE_DATA_0H                         0x0664
#define TVW_DUMMY_WRITE_DATA_1L                         0x0668
#define TVW_DUMMY_WRITE_DATA_1H                         0x066c
#define TVW_DUMMY_WRITE_DATA_2L                         0x0670
#define TVW_DUMMY_WRITE_DATA_2H                         0x0674
#define TVW_DUMMY_WRITE_DATA_3L                         0x0678
#define TVW_DUMMY_WRITE_DATA_3H                         0x067c
#define TVW_MEM_CLIENT_DISABLES                         0x0680
#define TVW_MEM_BLOCK_ACCESS_EFF_CLASS_CNTL             0x0698
#define TVW_MIPS_PROTECTED_BOTTOM_A                     0x06a0
#define TVW_MIPS_PROTECTED_TOP_A                        0x06a4
#define TVW_MIPS_PROTECTED_BOTTOM_B                     0x06a8
#define TVW_MIPS_PROTECTED_TOP_B                        0x06ac
#define TVW_MIPS_PROTECTED_BOTTOM_C                     0x06b0
#define TVW_MIPS_PROTECTED_TOP_C                        0x06b4
#define TVW_MIPS_PROTECTED_BOTTOM_D                     0x06b8
#define TVW_MIPS_PROTECTED_TOP_D                        0x06bc
#define TVW_HOST_PROTECTED_BOTTOM_A                     0x06c0
#define TVW_HOST_PROTECTED_TOP_A                        0x06c4
#define TVW_HOST_PROTECTED_BOTTOM_B                     0x06c8
#define TVW_HOST_PROTECTED_TOP_B                        0x06cc
#define TVW_HOST_PROTECTED_BOTTOM_C                     0x06d0
#define TVW_HOST_PROTECTED_TOP_C                        0x06d4
#define TVW_HOST_PROTECTED_BOTTOM_D                     0x06d8
#define TVW_HOST_PROTECTED_TOP_D                        0x06dc
#define TVW_MC_WATCHPOINT_SETUP                         0x06f0
#define TVW_MC_WATCHPOINT_BOTTOM                        0x06f4
#define TVW_MC_WATCHPOINT_TOP                           0x06f8
#define TVW_MC_WATCHPOINT_RESULT                        0x06fc
#define TVW_MC_GEN_RESET_CNTL                           0x0700
#define TVW_MC_TC_DBG_MUX                               0x0710
#define TVW_MC_TC_DBG_OUT                               0x0714
#define TVW_MEM_ADDR_OUT_OF_RANGE_STATUS                0x0720
#define TVW_MC_WATCHPOINT_STATUS                        0x0730
#define TVW_MIPS_PROTECTED_MEM_A_ERROR_STATUS           0x0740
#define TVW_MIPS_PROTECTED_MEM_B_ERROR_STATUS           0x0744
#define TVW_MIPS_PROTECTED_MEM_C_ERROR_STATUS           0x0748
#define TVW_MIPS_PROTECTED_MEM_D_ERROR_STATUS           0x074c
#define TVW_HOST_PROTECTED_MEM_A_ERROR_STATUS           0x0750
#define TVW_HOST_PROTECTED_MEM_B_ERROR_STATUS           0x0754
#define TVW_HOST_PROTECTED_MEM_C_ERROR_STATUS           0x0758
#define TVW_HOST_PROTECTED_MEM_D_ERROR_STATUS           0x075c
#define TVW_POWER_CONTROL                               0x0780
#define TVW_MEM_PERF_CONTROL                            0x0790
#define TVW_MEM_PERF_PRIMARY_COUNTER                    0x0794
#define TVW_MEM_PERF_COUNTER_2                          0x07a8
#define TVW_MEM_PERF_COUNTER_3                          0x07ac
#define TVW_MEM_PERF_COUNTER_4                          0x07b0
#define TVW_MEM_PERF_COUNTER_5                          0x07b4
#define TVW_MEM_PERF_COUNTER_6                          0x07b8
#define TVW_MEM_PERF_COUNTER_7                          0x07bc
#define TVW_MEM_PERF_COUNTER_8                          0x07c0
#define TVW_MEM_PERF_COUNTER_9                          0x07c4
#define TVW_MEM_PERF_COUNTER_10                         0x07c8
#define TVW_MEM_PERF_COUNTER_11                         0x07cc
#define TVW_MEM_PERF_COUNTER_13                         0x07d4
#define TVW_MEM_PERF_COUNTER_15                         0x07dc
#define TVW_MEM_PERF_COUNTER_16                         0x07e0
#define TVW_MEM_PERF_COUNTER_17                         0x07e4
#define TVW_MEM_PERF_COUNTER_18                         0x07e8
#define TVW_MEM_PERF_COUNTER_19                         0x07ec
#define TVW_MEM_PERF_COUNTER_20                         0x07f0
#define TVW_MEM_PERF_COUNTER_21                         0x07f4
#define TVW_MEM_PERF_COUNTER_22                         0x07f8
#define TVW_MC_PATCH_REG                                0x07fc
#define TVW_IC_STATUS                                   0x0800
#define TVW_CLOCK_CONTROL_0                             0x0804
#define TVW_CLOCK_CONTROL_1                             0x0808
#define TVW_RESET_CONTROL                               0x080c
#define TVW_SOFT_STRAPS_0                               0x0810
#define TVW_SOFT_STRAPS_1                               0x0814
#define TVW_SOFT_STRAPS_2                               0x0818
#define TVW_SOFT_STRAPS_3                               0x081c
#define TVW_GPIO_PORT_CONTROL                           0x0820
#define TVW_GPIO_PORT_TMUX                              0x0824
#define TVW_PCI_PORT_WDATA_0                            0x0828
#define TVW_PCI_PORT_WDATA_1                            0x082c
#define TVW_PCI_PORT_RDATA_0                            0x0830
#define TVW_PCI_PORT_RDATA_1                            0x0834
#define TVW_PCI_PORT_OE_0                               0x0838
#define TVW_PCI_PORT_OE_1                               0x083c
#define TVW_PCI_PORT_CONTROL                            0x0840
#define TVW_TSI_PORT_WDATA                              0x0844
#define TVW_TSI_PORT_RDATA                              0x0848
#define TVW_TSI_PORT_OE                                 0x084c
#define TVW_TSI_PORT_CONTROL                            0x0850
#define TVW_TSO_PORT_WDATA                              0x0854
#define TVW_TSO_PORT_RDATA                              0x0858
#define TVW_TSO_PORT_OE                                 0x085c
#define TVW_TSO_PORT_CONTROL                            0x0860
#define TVW_DVSO_PORT_WDATA                             0x0864
#define TVW_DVSO_PORT_RDATA                             0x0868
#define TVW_DVSO_PORT_OE                                0x086c
#define TVW_DVSO_PORT_CONTROL                           0x0870
#define TVW_I2S_PORT_WDATA                              0x0874
#define TVW_I2S_PORT_RDATA                              0x0878
#define TVW_I2S_PORT_OE                                 0x087c
#define TVW_I2S_PORT_CONTROL                            0x0880
#define TVW_AGC_PORT_CONTROL                            0x0884
#define TVW_OSC_CONTROL                                 0x0890
#define TVW_VIDEO_INPUT_0_CONTROL                       0x0894
#define TVW_VIDEO_ADC_0_CONTROL                         0x0898
#define TVW_VIDEO_INPUT_1_CONTROL                       0x089c
#define TVW_VIDEO_ADC_1_CONTROL                         0x08a0
#define TVW_MPLL_CONTROL                                0x08b0
#define TVW_FPLL_CONTROL                                0x08b4
#define TVW_XPLL_CONTROL                                0x08b8
#define TVW_VPLL_CONTROL_0                              0x08bc
#define TVW_VPLL_CONTROL_1                              0x08c0
#define TVW_APLL_CONTROL_0                              0x08c4
#define TVW_APLL_CONTROL_1                              0x08c8
#define TVW_APLL_CONTROL_2                              0x08cc
#define TVW_MC_CONTROL                                  0x08d0
#define TVW_MCIO_TEST                                   0x08d4
#define TVW_AVSYNC_STC_WINDOW                           0x08e0
#define TVW_AVSYNC_SCLK_WINDOW                          0x08e4
#define TVW_AVSYNC_AUDIO_GAIN                           0x08e8
#define TVW_AVSYNC_AUDIO_ACC_IN                         0x08ec
#define TVW_AVSYNC_VIDEO_GAIN                           0x08f0
#define TVW_AVSYNC_AUDIO_STATUS                         0x08f4
#define TVW_TEST_CONTROL                                0x0900
#define TVW_MBIST_CONTROL                               0x0910
#define TVW_AVBSI_TPA_CNTL                              0x0c00
#define TVW_AVBSI_FRAMER0_CNTL1                         0x0c04
#define TVW_AVBSI_FRAMER1_CNTL1                         0x0c08
#define TVW_AVBSI_FRAMER0_CNTL2                         0x0c0c
#define TVW_AVBSI_FRAMER1_CNTL2                         0x0c10
#define TVW_AVBSI_FRAMER0_LENGTH                        0x0c14
#define TVW_AVBSI_FRAMER1_LENGTH                        0x0c18
#define TVW_AVBSO_TNF_HSDP_CFG                          0x0c1c
#define TVW_AVBSIO_INTERRUPT_CLEAR                      0x0c20
#define TVW_AVBSIO_INTERRUPT_STATUS                     0x0c20
#define TVW_AVBSIO_INTERRUPT_MASK0                      0x0c24
#define TVW_AVBSIO_INTERRUPT_MASK1                      0x0c28
#define TVW_AVBSIO_INTERRUPT_MASK2                      0x0c2c
#define TVW_AVBSIO_INTERRUPT_FORCE                      0x0c30
#define TVW_AVBSIO_DEBUG_MUX                            0x0c3c
#define TVW_DVSI_SETTINGS                               0x0c40
#define TVW_DVSI_HEARTBEAT_CNT                          0x0c44
#define TVW_SMGR_INTERRUPT_CLEAR                        0x1000
#define TVW_SMGR_INTERRUPT_STATUS                       0x1000
#define TVW_SMGR_INTERRUPT_MASK0                        0x1004
#define TVW_SMGR_INTERRUPT_MASK1                        0x1008
#define TVW_SMGR_INTERRUPT_MASK2                        0x100c
#define TVW_SMGR_SOFT_RESETS                            0x1020
#define TVW_SMGR_DEBUG_CNTL                             0x1024
#define TVW_POWER_CNTL_RW                               0x1028
#define TVW_PATCH_REG                                   0x102c
#define TVW_DRS_INIT                                    0x1040
#define TVW_DRS_CONTROL                                 0x1044
#define TVW_DRS_FILL_COLOR                              0x1048
#define TVW_VSE_REF_CNT                                 0x1090
#define TVW_VSE_FULL_CYCLE_CNT                          0x1094
#define TVW_VSE_REF_CNT_CNTL                            0x1098
#define TVW_VSE_VSYNC_CNT                               0x109c
#define TVW_VSE_PREV_VSYNC_TIME                         0x10a0
#define TVW_VSE_TBC_CNTL                                0x10a4
#define TVW_FEVW_COMMAND                                0x1100
#define TVW_FEVW_SETTINGS                               0x1104
#define TVW_FEVW_ENGINE_STATUS                          0x1108
#define TVW_FEVW_STATUS                                 0x110c
#define TVW_FEVW_VID_START_LINE                         0x1110
#define TVW_FEVW_VBI_START_LINE                         0x1114
#define TVW_FEVW_VBI_START_PIXEL                        0x1118
#define TVW_FEVW_WIDTH                                  0x111c
#define TVW_FEVW_VBI_HEIGHT                             0x1120
#define TVW_FEVW_HEIGHT                                 0x1124
#define TVW_FEVW_N_FRAME_BUFS                           0x1128
#define TVW_FEVW_LUM_INT_OFFSET_1                       0x112c
#define TVW_FEVW_CHR_INT_OFFSET_1                       0x1130
#define TVW_FEVW_FRAC_OFFSET_1                          0x1134
#define TVW_FEVW_VBI_OFFSET_1                           0x1138
#define TVW_FEVW_LUM_INT_OFFSET_2                       0x113c
#define TVW_FEVW_CHR_INT_OFFSET_2                       0x1140
#define TVW_FEVW_FRAC_OFFSET_2                          0x1144
#define TVW_FEVW_VBI_OFFSET_2                           0x1148
#define TVW_FEVW_LUM_INT_PITCH                          0x114c
#define TVW_FEVW_CHR_INT_PITCH                          0x1150
#define TVW_FEVW_FRAC_PITCH                             0x1154
#define TVW_FEVW_VBI_PITCH                              0x1158
#define TVW_FEVW_OLD_STATUS                             0x116c
#define TVW_FEVW_ACK_FIELDS                             0x1180
#define TVW_FEVW_FIELDS_INT_THR                         0x1184
#define TVW_FEVW_NUMLINES_BUF_0                         0x1188
#define TVW_FEVW_NUMLINES_BUF_1                         0x118c
#define TVW_FEVW_NUMLINES_BUF_2                         0x1190
#define TVW_FEVW_NUMLINES_BUF_3                         0x1194
#define TVW_FEVW_NUMLINES_BUF_4                         0x1198
#define TVW_FEVW_NUMLINES_BUF_5                         0x119c
#define TVW_FEVW_NUMLINES_BUF_6                         0x11a0
#define TVW_FEVW_NUMLINES_BUF_7                         0x11a4
#define TVW_FEVW_NUMLINES_BUF_8                         0x11a8
#define TVW_FEVW_NUMLINES_BUF_9                         0x11ac
#define TVW_FEVW_NUMLINES_BUF_10                        0x11b0
#define TVW_FEVW_NUMLINES_BUF_11                        0x11b4
#define TVW_FEVW_NUMLINES_BUF_12                        0x11b8
#define TVW_FEVW_NUMLINES_BUF_13                        0x11bc
#define TVW_FEVW_NUMLINES_BUF_14                        0x11c0
#define TVW_FEVW_NUMLINES_BUF_15                        0x11c4
#define TVW_FEVW_VSTART_TIME_0                          0x11c8
#define TVW_FEVW_VSTART_TIME_1                          0x11cc
#define TVW_FEVW_VSTART_TIME_2                          0x11d0
#define TVW_FEVW_VSTART_TIME_3                          0x11d4
#define TVW_FEVW_VSTART_TIME_4                          0x11d8
#define TVW_FEVW_VSTART_TIME_5                          0x11dc
#define TVW_FEVW_VSTART_TIME_6                          0x11e0
#define TVW_FEVW_VSTART_TIME_7                          0x11e4
#define TVW_DVSO_CRTC_SETTINGS                          0x1200
#define TVW_DVSO_CRTC_VSTART                            0x1204
#define TVW_DVSO_CRTC_VBI_START_LINE                    0x1208
#define TVW_DVSO_CRTC_VID_START_LINE                    0x120c
#define TVW_DVSO_CRTC_STATUS                            0x1210
#define TVW_DVSO_CRTC_VLINE_INTR                        0x1214
#define TVW_SMGR_BIST_SEL                               0x1240
#define TVW_VBIST_VID_HEIGHT                            0x1244
#define TVW_VBIST_VID_WIDTH                             0x1248
#define TVW_VBIST_VBI_HEIGHT                            0x124c
#define TVW_VBIST_GENERATOR                             0x1254
#define TVW_VBIST_BURST_LEVEL                           0x1258
#define TVW_VBIST_SPRITE                                0x125c
#define TVW_VBIST_RESET                                 0x1260
#define TVW_ABIST_SETTINGS                              0x1270
#define TVW_ABIST_INC_SIZE                              0x1274
#define TVW_RVR_COMMAND                                 0x1280
#define TVW_RVR_START_CONDITIONS                        0x1284
#define TVW_RVR_SETTINGS                                0x1288
#define TVW_RVR_ENGINE_STATUS                           0x128c
#define TVW_RVR_STATUS                                  0x1290
#define TVW_RVR_WIDTH                                   0x1294
#define TVW_RVR_HEIGHT                                  0x1298
#define TVW_RVR_VBI_HEIGHT                              0x129c
#define TVW_RVR_N_FRAME_BUFS                            0x12a0
#define TVW_RVR_LUM_INT_OFFSET_1                        0x12a4
#define TVW_RVR_CHR_INT_OFFSET_1                        0x12a8
#define TVW_RVR_FRAC_OFFSET_1                           0x12ac
#define TVW_RVR_VBI_OFFSET_1                            0x12b0
#define TVW_RVR_LUM_INT_OFFSET_2                        0x12b4
#define TVW_RVR_CHR_INT_OFFSET_2                        0x12b8
#define TVW_RVR_FRAC_OFFSET_2                           0x12bc
#define TVW_RVR_VBI_OFFSET_2                            0x12c0
#define TVW_RVR_LUM_INT_PITCH                           0x12c4
#define TVW_RVR_CHR_INT_PITCH                           0x12c8
#define TVW_RVR_FRAC_PITCH                              0x12cc
#define TVW_RVR_VBI_PITCH                               0x12d0
#define TVW_RVR_ADV_ON_OVF                              0x12d4
#define TVW_RVR_ADV_ON_CRTC_UNDF                        0x12d8
#define TVW_RVR_VLINE_INT_THR                           0x12dc
#define TVW_RVR_DROPPED_PIXEL_CNT                       0x12e0
#define TVW_RVR_TBC                                     0x12e4
#define TVW_FW_VMOW_STATUS                              0x1300
#define TVW_FW_VMOW_OLD_POSITION                        0x1304
#define TVW_FW_VMW_STATUS                               0x1318
#define TVW_FW_VMW_POSITION                             0x131c
#define TVW_VBW_SETTINGS                                0x1400
#define TVW_VBW_STATUS                                  0x1404
#define TVW_VBW_LUM_DDT_FLAGS                           0x1408
#define TVW_VBW_CHR_DDT_FLAGS                           0x140c
#define TVW_VBW_VBI_DDT_FLAGS                           0x1410
#define TVW_VBW_LUM_DDT_COUNT                           0x1414
#define TVW_VBW_CHR_DDT_COUNT                           0x1418
#define TVW_VBW_VBI_DDT_COUNT                           0x141c
#define TVW_VBW_LUM_DDT_POS                             0x1420
#define TVW_VBW_CHR_DDT_POS                             0x1424
#define TVW_VBW_VBI_DDT_POS                             0x1428
#define TVW_VBW_LUM_DDTE_POS                            0x142c
#define TVW_VBW_VBI_DDTE_POS                            0x1430
#define TVW_VBW_LUM_DDT_ADDR                            0x1434
#define TVW_VBW_CHR_DDT_ADDR                            0x1438
#define TVW_VBW_VBI_DDT_ADDR                            0x143c
#define TVW_RVR_VID_FIELDS_INT_THR                      0x1440
#define TVW_RVR_VBI_FIELDS_INT_THR                      0x1444
#define TVW_RVR_ACK_VID_FIELDS                          0x1448
#define TVW_RVR_ACK_VBI_FIELDS                          0x144c
#define TVW_AUD_SCRAMBLE_INIT                           0x1500
#define TVW_AUD_SCRAMBLE_CONTROL                        0x1504
#define TVW_FEAW_COMMAND                                0x1540
#define TVW_FEAW_ENGINE_STATUS                          0x1544
#define TVW_FEAW_SETTINGS                               0x1548
#define TVW_FEAW_OFFSET                                 0x154c
#define TVW_FEAW_CYCLE_CNT                              0x1550
#define TVW_FEAW_WRITE_PTR                              0x1554
#define TVW_FEAW_OLD_WRITE_PTR                          0x1558
#define TVW_FEAW_ACK_SAMPLES                            0x155c
#define TVW_FEAW_SAMPLES_INT_THR                        0x1560
#define TVW_RAR_COMMAND                                 0x1580
#define TVW_RAR_SETTINGS                                0x1584
#define TVW_RAR_ENGINE_STATUS                           0x1588
#define TVW_RAR_BUF_SIZE                                0x158c
#define TVW_RAR_OFFSET                                  0x1590
#define TVW_RAR_START_WATERMARK                         0x1594
#define TVW_RAR_SAMPLE_CNT                              0x1598
#define TVW_RAR_READ_PTR                                0x159c
#define TVW_RAR_DROPPED_SAMPLE_CNT                      0x15a0
#define TVW_FW_AMW_STATUS                               0x15c0
#define TVW_FW_AMW_WRITE_PTR                            0x15c4
#define TVW_FW_AMOW_STATUS                              0x15c8
#define TVW_FW_AMOW_OLD_WRITE_PTR                       0x15cc
#define TVW_ABW_SETTINGS                                0x1640
#define TVW_ABW_STATUS                                  0x1644
#define TVW_ABW_DDT_FLAGS                               0x1648
#define TVW_ABW_DDT_COUNT                               0x164c
#define TVW_ABW_DDT_POS                                 0x1650
#define TVW_ABW_DDTE_POS                                0x1654
#define TVW_ABW_DDT_ADDR                                0x1658
#define TVW_ABW_BUFS_INT_THR                            0x165c
#define TVW_ABW_ACK_BUFS                                0x1660
#define TVW_AVBS1W_COMMAND                              0x1800
#define TVW_AVBS1W_SETTINGS                             0x1804
#define TVW_AVBS1W_ENGINE_STATUS                        0x1808
#define TVW_AVBS1W_BUF_SIZE                             0x180c
#define TVW_AVBS1W_OFFSET                               0x1810
#define TVW_AVBS1W_CYCLE_CNT                            0x1814
#define TVW_AVBS1W_WRITE_PTR                            0x1818
#define TVW_AVBS1W_OLD_WRITE_PTR                        0x181c
#define TVW_AVBS1W_ACK_BYTES                            0x1820
#define TVW_AVBS1W_BYTES_INT_THR                        0x1824
#define TVW_AVBS1R_COMMAND                              0x1840
#define TVW_AVBS1R_SETTINGS                             0x1844
#define TVW_AVBS1R_ENGINE_STATUS                        0x1848
#define TVW_AVBS1R_START_WATERMARK                      0x184c
#define TVW_AVBS1R_BUF_SIZE                             0x1850
#define TVW_AVBS1R_OFFSET                               0x1854
#define TVW_AVBS1R_BYTE_CNT                             0x1858
#define TVW_AVBS1R_READ_PTR                             0x185c
#define TVW_AVBS1R_DROPPED_BYTE_CNT                     0x1860
#define TVW_AVBS1R_CSCR_CMD_0                           0x1864
#define TVW_AVBS1R_CSCR_CMD_1                           0x1868
#define TVW_AVBS1R_CSCR_BYTE_CNT                        0x186c
#define TVW_AVBS1R_CSCR_READ_PTR                        0x1870
#define TVW_AVBS1R_OUT_BYTE_CNT                         0x1874
#define TVW_AVBS1R_FIFO_DATA_CNT                        0x1878
#define TVW_FW_AVBS1MW_STATUS                           0x1880
#define TVW_FW_AVBS1MW_WRITE_PTR                        0x1884
#define TVW_FW_AVBS1MOW_STATUS                          0x1888
#define TVW_FW_AVBS1MOW_OLD_WRITE_PTR                   0x188c
#define TVW_RNG_CNTL_STATUS                             0x1894
#define TVW_RNG_LFSR_SEED                               0x1898
#define TVW_RNG_WORD_REGISTERS                          0x189c
#define TVW_AES1_KEY0_0                                 0x18a0
#define TVW_AES1_KEY0_1                                 0x18a4
#define TVW_AES1_KEY0_2                                 0x18a8
#define TVW_AES1_KEY0_3                                 0x18ac
#define TVW_AES1_KEY1_0                                 0x18b0
#define TVW_AES1_KEY1_1                                 0x18b4
#define TVW_AES1_KEY1_2                                 0x18b8
#define TVW_AES1_KEY1_3                                 0x18bc
#define TVW_AES1_COUNTER_0                              0x18c0
#define TVW_AES1_COUNTER_1                              0x18c4
#define TVW_AES1_UPPER_IV_0                             0x18c8
#define TVW_AES1_UPPER_IV_1                             0x18cc
#define TVW_AES1_DATA_IN_0                              0x18d0
#define TVW_AES1_DATA_IN_1                              0x18d4
#define TVW_AES1_DATA_IN_2                              0x18d8
#define TVW_AES1_DATA_IN_3                              0x18dc
#define TVW_AES1_DATA_OUT_0                             0x18e0
#define TVW_AES1_DATA_OUT_1                             0x18e4
#define TVW_AES1_DATA_OUT_2                             0x18e8
#define TVW_AES1_DATA_OUT_3                             0x18ec
#define TVW_AES1_COUNTER_CNTL                           0x18f0
#define TVW_AES1_CNTL_0                                 0x18f4
#define TVW_AES1_CNTL_1                                 0x18f8
#define TVW_AVBS1BW_SETTINGS                            0x1900
#define TVW_AVBS1BW_STATUS                              0x1904
#define TVW_AVBS1BW_DDT_FLAGS                           0x1908
#define TVW_AVBS1BW_DDT_COUNT                           0x190c
#define TVW_AVBS1BW_DDT_POS                             0x1910
#define TVW_AVBS1BW_DDTE_POS                            0x1914
#define TVW_AVBS1BW_DDT_ADDR                            0x1918
#define TVW_AVBS1BW_BUFS_INT_THR                        0x191c
#define TVW_AVBS1BW_ACK_BUFS                            0x1920
#define TVW_AVBS2W_COMMAND                              0x1a00
#define TVW_AVBS2W_SETTINGS                             0x1a04
#define TVW_AVBS2W_ENGINE_STATUS                        0x1a08
#define TVW_AVBS2W_BUF_SIZE                             0x1a0c
#define TVW_AVBS2W_OFFSET                               0x1a10
#define TVW_AVBS2W_CYCLE_CNT                            0x1a14
#define TVW_AVBS2W_WRITE_PTR                            0x1a18
#define TVW_AVBS2W_OLD_WRITE_PTR                        0x1a1c
#define TVW_AVBS2W_ACK_BYTES                            0x1a20
#define TVW_AVBS2W_BYTES_INT_THR                        0x1a24
#define TVW_AVBS2R_COMMAND                              0x1a40
#define TVW_AVBS2R_SETTINGS                             0x1a44
#define TVW_AVBS2R_ENGINE_STATUS                        0x1a48
#define TVW_AVBS2R_START_WATERMARK                      0x1a4c
#define TVW_AVBS2R_BUF_SIZE                             0x1a50
#define TVW_AVBS2R_OFFSET                               0x1a54
#define TVW_AVBS2R_BYTE_CNT                             0x1a58
#define TVW_AVBS2R_READ_PTR                             0x1a5c
#define TVW_AVBS2R_DROPPED_BYTE_CNT                     0x1a60
#define TVW_AVBS2R_CSCR_CMD_0                           0x1a64
#define TVW_AVBS2R_CSCR_CMD_1                           0x1a68
#define TVW_AVBS2R_CSCR_BYTE_CNT                        0x1a6c
#define TVW_AVBS2R_CSCR_READ_PTR                        0x1a70
#define TVW_AVBS2R_OUT_BYTE_CNT                         0x1a74
#define TVW_AVBS2R_FIFO_DATA_CNT                        0x1a78
#define TVW_FW_AVBS2MW_STATUS                           0x1a80
#define TVW_FW_AVBS2MW_WRITE_PTR                        0x1a84
#define TVW_FW_AVBS2MOW_STATUS                          0x1a88
#define TVW_FW_AVBS2MOW_OLD_WRITE_PTR                   0x1a8c
#define TVW_AVBS2BW_SETTINGS                            0x1b00
#define TVW_AVBS2BW_STATUS                              0x1b04
#define TVW_AVBS2BW_DDT_FLAGS                           0x1b08
#define TVW_AVBS2BW_DDT_COUNT                           0x1b0c
#define TVW_AVBS2BW_DDT_POS                             0x1b10
#define TVW_AVBS2BW_DDTE_POS                            0x1b14
#define TVW_AVBS2BW_DDT_ADDR                            0x1b18
#define TVW_AVBS2BW_BUFS_INT_THR                        0x1b1c
#define TVW_AVBS2BW_ACK_BUFS                            0x1b20
#define TVW_USC_VB_START                                0x2000
#define TVW_USC_VB_FINISH                               0x2004
#define TVW_USC_FLD_ID                                  0x2008
#define TVW_USC_CTL                                     0x200c
#define TVW_USC_ANC_ID                                  0x2010
#define TVW_USC_ANC_WIDTH                               0x2014
#define TVW_USC_FIFO_STATUS                             0x2018
#define TVW_USC_VD_START                                0x201c
#define TVW_USC_VD_FINISH                               0x2020
#define TVW_USC_INTR_CLEAR                              0x2024
#define TVW_USC_INTR_STATUS                             0x2024
#define TVW_USC_DEBUG_CTL                               0x2028
#define TVW_AGC_SRAM_BASE                               0x4000
#define TVW_AGC_ADC_MODE                                0x4300
#define TVW_AGC_CONTROL                                 0x4304
#define TVW_AGC_ADC_TARGET_POWER_LEVEL                  0x4308
#define TVW_AGC_ADC_POWER_LPF_FC                        0x430c
#define TVW_AGC_ADC_POWER_DETECT                        0x4310
#define TVW_AGC_GAIN_LOOP_BANDWIDTH                     0x4314
#define TVW_AGC_GAIN_DISTRIBUTION_LOOP_BANDWIDTH        0x4318
#define TVW_AGC_LOOP_DAMPING_RATIOS                     0x431c
#define TVW_AGC_ACCUMULATOR1                            0x4320
#define TVW_AGC_ACCUMULATOR2                            0x4324
#define TVW_AGC_KG1                                     0x4328
#define TVW_AGC_KG2                                     0x432c
#define TVW_AGC_KD1                                     0x4330
#define TVW_AGC_KD2                                     0x4334
#define TVW_AGC_PDET_TARGET_POWER_LEVEL                 0x4338
#define TVW_AGC_PDET_PARAMETERS                         0x433c
#define TVW_AGC_PDET_POWER                              0x4340
#define TVW_AGC_SDM12_LPF_FC                            0x4344
#define TVW_AGC_SDMXA_LPF_FC                            0x4348
#define TVW_AGC_SDM_CONFIGURE                           0x434c
#define TVW_AGC_SDM1_INPUT                              0x4350
#define TVW_AGC_SDM2_INPUT                              0x4354
#define TVW_AGC_SDMX_INPUT                              0x4358
#define TVW_AGC_ACCUMULATOR1_MAX                        0x435c
#define TVW_AGC_ACCUMULATOR1_MIN                        0x4360
#define TVW_AGC_ACCUMULATOR2_MAX                        0x4364
#define TVW_AGC_ACCUMULATOR2_MIN                        0x4368
#define TVW_AGC_NTSC_HOLD_LINE_NUMBER                   0x436c
#define TVW_AGC_ADC_DATA_MIN                            0x4370
#define TVW_AGC_ADC_DATA_MAX                            0x4374
#define TVW_AGC_HALF_SYNC_LENGTH                        0x4378
#define TVW_AGC_FULL_SYNC_LENGTH                        0x437c
#define TVW_AGC_WIDE_SYNC_LENGTH                        0x4380
#define TVW_AGC_SRAM_DOWNLOAD                           0x4384
#define TVW_FE_DC_CONTROL                               0x4400
#define TVW_FE_DC_NORMALIZED_IF                         0x4404
#define TVW_FE_DC_NORMALIZED_VIDEO_FREQ                 0x4408
#define TVW_FE_DC_CO_STATUS                             0x440c
#define TVW_FE_IAGC_CONTROL                             0x4410
#define TVW_FE_IAGC_TARGET_POWER                        0x4414
#define TVW_FE_IAGC_ERR_THRESHOLD                       0x4418
#define TVW_FE_IAGC_BLK_LGTH                            0x441c
#define TVW_FE_IAGC_GAIN                                0x4420
#define TVW_FE_IAGC_K1_K2                               0x4424
#define TVW_FE_IAGC_MAX_OUT                             0x4428
#define TVW_FE_IAGC_PSD_SUM                             0x442c
#define TVW_FE_PILOT_CONTROL                            0x4430
#define TVW_FE_PILOT_LPF_GAIN                           0x4434
#define TVW_FE_PILOT_K1_K2                              0x4438
#define TVW_FE_PILOT_FREQ_RST_COUNT                     0x443c
#define TVW_FE_PILOT_AMP                                0x4440
#define TVW_FE_PILOT_FQ_OFF                             0x4444
#define TVW_FE_PILOT_NORMALIZED_VIDEO_FREQ              0x4448
#define TVW_FE_PILOT_MIN_SIGNAL                         0x444c
#define TVW_FE_PILOT_MAX_SIGNAL                         0x4450
#define TVW_FE_TESTMUX_MODE                             0x4454
#define TVW_FE_CFILT_VSHIFT_IN                          0x4458
#define TVW_FE_CFILT_VSHIFT_OUT                         0x445c
#define TVW_FE_CFILT_BACKPHASE                          0x4460
#define TVW_FE_DEROT_BPASS                              0x4464
#define TVW_FE_PILOT_FQ_OFF_MIN                         0x4468
#define TVW_FE_PILOT_FQ_OFF_MAX                         0x446c
#define TVW_FE_VFILT_COEF_0_0                           0x4480
#define TVW_FE_VFILT_COEF_0_1                           0x4484
#define TVW_FE_VFILT_COEF_0_2                           0x4488
#define TVW_FE_VFILT_COEF_0_3                           0x448c
#define TVW_FE_VFILT_COEF_0_4                           0x4490
#define TVW_FE_VFILT_COEF_0_5                           0x4494
#define TVW_FE_VFILT_COEF_0_6                           0x4498
#define TVW_FE_VFILT_COEF_0_7                           0x449c
#define TVW_FE_VFILT_COEF_1_0                           0x44a0
#define TVW_FE_VFILT_COEF_1_1                           0x44a4
#define TVW_FE_VFILT_COEF_1_2                           0x44a8
#define TVW_FE_VFILT_COEF_1_3                           0x44ac
#define TVW_FE_VFILT_COEF_1_4                           0x44b0
#define TVW_FE_VFILT_COEF_1_5                           0x44b4
#define TVW_FE_VFILT_COEF_1_6                           0x44b8
#define TVW_FE_VFILT_COEF_1_7                           0x44bc
#define TVW_FE_VFILT_COEF_2_0                           0x44c0
#define TVW_FE_VFILT_COEF_2_1                           0x44c4
#define TVW_FE_VFILT_COEF_2_2                           0x44c8
#define TVW_FE_VFILT_COEF_2_3                           0x44cc
#define TVW_FE_VFILT_COEF_2_4                           0x44d0
#define TVW_FE_VFILT_COEF_2_5                           0x44d4
#define TVW_FE_VFILT_COEF_2_6                           0x44d8
#define TVW_FE_VFILT_COEF_2_7                           0x44dc
#define TVW_FE_VFILT_COEF_3_0                           0x44e0
#define TVW_FE_VFILT_COEF_3_1                           0x44e4
#define TVW_FE_VFILT_COEF_3_2                           0x44e8
#define TVW_FE_VFILT_COEF_3_3                           0x44ec
#define TVW_FE_VFILT_COEF_3_4                           0x44f0
#define TVW_FE_VFILT_COEF_3_5                           0x44f4
#define TVW_FE_VFILT_COEF_3_6                           0x44f8
#define TVW_FE_VFILT_COEF_3_7                           0x44fc
#define TVW_FE_VFILT_COEF_4_0                           0x4500
#define TVW_FE_VFILT_COEF_4_1                           0x4504
#define TVW_FE_VFILT_COEF_4_2                           0x4508
#define TVW_FE_VFILT_COEF_4_3                           0x450c
#define TVW_FE_VFILT_COEF_4_4                           0x4510
#define TVW_FE_VFILT_COEF_4_5                           0x4514
#define TVW_FE_VFILT_COEF_4_6                           0x4518
#define TVW_FE_VFILT_COEF_4_7                           0x451c
#define TVW_FE_VFILT_COEF_5_0                           0x4520
#define TVW_FE_VFILT_COEF_5_1                           0x4524
#define TVW_FE_VFILT_COEF_5_2                           0x4528
#define TVW_FE_VFILT_COEF_5_3                           0x452c
#define TVW_FE_VFILT_COEF_5_4                           0x4530
#define TVW_FE_VFILT_COEF_5_5                           0x4534
#define TVW_FE_VFILT_COEF_5_6                           0x4538
#define TVW_FE_VFILT_COEF_5_7                           0x453c
#define TVW_FE_VFILT_COEF_6_0                           0x4540
#define TVW_FE_VFILT_COEF_6_1                           0x4544
#define TVW_FE_VFILT_COEF_6_2                           0x4548
#define TVW_FE_VFILT_COEF_6_3                           0x454c
#define TVW_FE_VFILT_COEF_6_4                           0x4550
#define TVW_FE_VFILT_COEF_6_5                           0x4554
#define TVW_FE_VFILT_COEF_6_6                           0x4558
#define TVW_FE_VFILT_COEF_6_7                           0x455c
#define TVW_FE_VFILT_COEF_7_0                           0x4560
#define TVW_FE_VFILT_COEF_7_1                           0x4564
#define TVW_FE_VFILT_COEF_7_2                           0x4568
#define TVW_FE_VFILT_COEF_7_3                           0x456c
#define TVW_FE_VFILT_COEF_7_4                           0x4570
#define TVW_FE_VFILT_COEF_7_5                           0x4574
#define TVW_FE_VFILT_COEF_7_6                           0x4578
#define TVW_FE_VFILT_COEF_7_7                           0x457c
#define TVW_NTSC_VSB_FILT_OUT_RANGE                     0x4580
#define TVW_NTSC_COMP_FILT_OUT_RANGE_I                  0x4584
#define TVW_NTSC_COMP_FILT_OUT_RANGE_Q                  0x4588
#define TVW_NTSC_DEROT_OUT_RANGE_I                      0x458c
#define TVW_NTSC_DEROT_OUT_RANGE_Q                      0x4590
#define TVW_NTSC_DOWNCONVERTER_RANGE_I                  0x4594
#define TVW_NTSC_DOWNCONVERTER_RANGE_Q                  0x4598
#define TVW_FE_CFILT_COEF_0_0                           0x459c
#define TVW_FE_CFILT_COEF_0_1                           0x45a0
#define TVW_FE_CFILT_COEF_0_2                           0x45a4
#define TVW_FE_CFILT_COEF_0_3                           0x45a8
#define TVW_FE_CFILT_COEF_0_4                           0x45ac
#define TVW_FE_CFILT_COEF_0_5                           0x45b0
#define TVW_FE_CFILT_COEF_0_6                           0x45b4
#define TVW_FE_CFILT_COEF_0_7                           0x45b8
#define TVW_FE_CFILT_COEF_1_0                           0x45bc
#define TVW_FE_CFILT_COEF_1_1                           0x45c0
#define TVW_FE_CFILT_COEF_1_2                           0x45c4
#define TVW_FE_CFILT_COEF_1_3                           0x45c8
#define TVW_FE_CFILT_COEF_1_4                           0x45cc
#define TVW_FE_CFILT_COEF_1_5                           0x45d0
#define TVW_FE_CFILT_COEF_1_6                           0x45d4
#define TVW_FE_CFILT_COEF_1_7                           0x45d8
#define TVW_FE_CFILT_COEF_2_0                           0x45dc
#define TVW_FE_CFILT_COEF_2_1                           0x45e0
#define TVW_FE_CFILT_COEF_2_2                           0x45e4
#define TVW_FE_CFILT_COEF_2_3                           0x45e8
#define TVW_FE_CFILT_COEF_2_4                           0x45ec
#define TVW_FE_CFILT_COEF_2_5                           0x45f0
#define TVW_FE_CFILT_COEF_2_6                           0x45f4
#define TVW_FE_CFILT_COEF_2_7                           0x45f8
#define TVW_FE_CFILT_COEF_3_0                           0x45fc
#define TVW_FE_CFILT_COEF_3_1                           0x4600
#define TVW_FE_CFILT_COEF_3_2                           0x4604
#define TVW_FE_CFILT_COEF_3_3                           0x4608
#define TVW_FE_CFILT_COEF_3_4                           0x460c
#define TVW_FE_CFILT_COEF_3_5                           0x4610
#define TVW_FE_CFILT_COEF_3_6                           0x4614
#define TVW_FE_CFILT_COEF_3_7                           0x4618
#define TVW_FE_CFILT_COEF_4_0                           0x461c
#define TVW_FE_CFILT_COEF_4_1                           0x4620
#define TVW_FE_CFILT_COEF_4_2                           0x4624
#define TVW_FE_CFILT_COEF_4_3                           0x4628
#define TVW_FE_CFILT_COEF_4_4                           0x462c
#define TVW_FE_CFILT_COEF_4_5                           0x4630
#define TVW_FE_CFILT_COEF_4_6                           0x4634
#define TVW_FE_CFILT_COEF_4_7                           0x4638
#define TVW_FE_CFILT_COEF_5_0                           0x463c
#define TVW_FE_CFILT_COEF_5_1                           0x4640
#define TVW_FE_CFILT_COEF_5_2                           0x4644
#define TVW_FE_CFILT_COEF_5_3                           0x4648
#define TVW_FE_CFILT_COEF_5_4                           0x464c
#define TVW_FE_CFILT_COEF_5_5                           0x4650
#define TVW_FE_CFILT_COEF_5_6                           0x4654
#define TVW_FE_CFILT_COEF_5_7                           0x4658
#define TVW_FE_CFILT_COEF_6_0                           0x465c
#define TVW_FE_CFILT_COEF_6_1                           0x4660
#define TVW_FE_CFILT_COEF_6_2                           0x4664
#define TVW_FE_CFILT_COEF_6_3                           0x4668
#define TVW_FE_CFILT_COEF_6_4                           0x466c
#define TVW_FE_CFILT_COEF_6_5                           0x4670
#define TVW_FE_CFILT_COEF_6_6                           0x4674
#define TVW_FE_CFILT_COEF_6_7                           0x4678
#define TVW_FE_CFILT_COEF_7_0                           0x467c
#define TVW_FE_CFILT_COEF_7_1                           0x4680
#define TVW_FE_CFILT_COEF_7_2                           0x4684
#define TVW_FE_CFILT_COEF_7_3                           0x4688
#define TVW_FE_CFILT_COEF_7_4                           0x468c
#define TVW_FE_CFILT_COEF_7_5                           0x4690
#define TVW_FE_CFILT_COEF_7_6                           0x4694
#define TVW_FE_CFILT_COEF_7_7                           0x4698
#define TVW_FE_BW_COEF_0_0                              0x469c
#define TVW_FE_BW_COEF_0_1                              0x46a0
#define TVW_FE_BW_COEF_0_2                              0x46a4
#define TVW_FE_BW_COEF_0_3                              0x46a8
#define TVW_FE_BW_COEF_0_4                              0x46ac
#define TVW_FE_BW_COEF_0_5                              0x46b0
#define TVW_FE_BW_COEF_0_6                              0x46b4
#define TVW_FE_BW_COEF_0_7                              0x46b8
#define TVW_FE_BW_COEF_1_0                              0x46bc
#define TVW_FE_BW_COEF_1_1                              0x46c0
#define TVW_FE_BW_COEF_1_2                              0x46c4
#define TVW_FE_BW_COEF_1_3                              0x46c8
#define TVW_FE_BW_COEF_1_4                              0x46cc
#define TVW_FE_BW_COEF_1_5                              0x46d0
#define TVW_FE_BW_COEF_1_6                              0x46d4
#define TVW_FE_BW_COEF_1_7                              0x46d8
#define TVW_FE_BW_COEF_2_0                              0x46dc
#define TVW_FE_BW_COEF_2_1                              0x46e0
#define TVW_FE_BW_COEF_2_2                              0x46e4
#define TVW_FE_BW_COEF_2_3                              0x46e8
#define TVW_FE_BW_COEF_2_4                              0x46ec
#define TVW_FE_BW_COEF_2_5                              0x46f0
#define TVW_FE_BW_COEF_2_6                              0x46f4
#define TVW_FE_BW_COEF_2_7                              0x46f8
#define TVW_FE_BW_COEF_3_0                              0x46fc
#define TVW_FE_BW_COEF_3_1                              0x4700
#define TVW_FE_BW_COEF_3_2                              0x4704
#define TVW_FE_BW_COEF_3_3                              0x4708
#define TVW_FE_BW_COEF_3_4                              0x470c
#define TVW_FE_BW_COEF_3_5                              0x4710
#define TVW_FE_BW_COEF_3_6                              0x4714
#define TVW_FE_BW_COEF_3_7                              0x4718
#define TVW_FE_BW_COEF_4_0                              0x471c
#define TVW_FE_BW_COEF_4_1                              0x4720
#define TVW_FE_BW_COEF_4_2                              0x4724
#define TVW_FE_BW_COEF_4_3                              0x4728
#define TVW_FE_BW_COEF_4_4                              0x472c
#define TVW_FE_BW_COEF_4_5                              0x4730
#define TVW_FE_BW_COEF_4_6                              0x4734
#define TVW_FE_BW_COEF_4_7                              0x4738
#define TVW_FE_BW_COEF_5_0                              0x473c
#define TVW_FE_BW_COEF_5_1                              0x4740
#define TVW_FE_BW_COEF_5_2                              0x4744
#define TVW_FE_BW_COEF_5_3                              0x4748
#define TVW_FE_BW_COEF_5_4                              0x474c
#define TVW_FE_BW_COEF_5_5                              0x4750
#define TVW_FE_BW_COEF_5_6                              0x4754
#define TVW_FE_BW_COEF_5_7                              0x4758
#define TVW_FE_BW_COEF_6_0                              0x475c
#define TVW_FE_BW_COEF_6_1                              0x4760
#define TVW_FE_BW_COEF_6_2                              0x4764
#define TVW_FE_BW_COEF_6_3                              0x4768
#define TVW_FE_BW_COEF_6_4                              0x476c
#define TVW_FE_BW_COEF_6_5                              0x4770
#define TVW_FE_BW_COEF_6_6                              0x4774
#define TVW_FE_BW_COEF_6_7                              0x4778
#define TVW_FE_BW_COEF_7_0                              0x477c
#define TVW_FE_BW_COEF_7_1                              0x4780
#define TVW_FE_BW_COEF_7_2                              0x4784
#define TVW_FE_BW_COEF_7_3                              0x4788
#define TVW_FE_BW_COEF_7_4                              0x478c
#define TVW_FE_BW_COEF_7_5                              0x4790
#define TVW_FE_BW_COEF_7_6                              0x4794
#define TVW_FE_BW_COEF_7_7                              0x4798
#define TVW_NTSC_CF_AUDIO_MAG_SHIFT                     0x4804
#define TVW_NTSC_DAC_DATA_FORMAT                        0x4808
#define TVW_NTSC_STATE_MACHINE_STATUS                   0x480c
#define TVW_NTSC_STATE_MACHINE_CONTROL                  0x4810
#define TVW_NTSC_FREQ_RESP_ADJUST_COEFF                 0x4814
#define TVW_NTSC_GAIN_ADJUST_FOR_DAC                    0x4818
#define TVW_NTSC_CLAMP_ADJUSTMENT                       0x481c
#define TVW_NTSC_TOTAL_PROCESSING_DELAY                 0x4820
#define TVW_NTSC_ACQUIRE_WINDOW_LENGTH                  0x4828
#define TVW_NTSC_HORIZONTAL_CONFIRM_WINDOW_LENGTH       0x482c
#define TVW_NTSC_HORIZONTAL_LOCK_WINDOW_LENGTH          0x4830
#define TVW_NTSC_HORIZONTAL_LOCK_COUNT                  0x4834
#define TVW_NTSC_MAXIMUM_HORIZONTAL_LOCK_COUNT          0x4838
#define TVW_NTSC_VERTICAL_LOCK_WINDOW_LENGTH            0x484c
#define TVW_NTSC_VERTICAL_LOCK_COUNT                    0x4850
#define TVW_NTSC_MAXIMUM_VERTICAL_LOCK_COUNT            0x4854
#define TVW_NTSC_SYNC_LENGTH                            0x4860
#define TVW_NTSC_MINIMUM_SYNC_LENGTH                    0x4864
#define TVW_NTSC_SYNC_LEVEL                             0x4868
#define TVW_NTSC_BURST_LEVEL                            0x486c
#define TVW_NTSC_BURST_LENGTH_FOR_AGC                   0x4874
#define TVW_NTSC_SYNC_LENGTH_FOR_AGC                    0x4878
#define TVW_NTSC_SYNC_BURST_EDGE_FOR_AGC                0x487c
#define TVW_NTSC_MAX_SYNC_TIP_EDGE                      0x4880
#define TVW_NTSC_SYNC_TIP_EDGE                          0x4884
#define TVW_NTSC_GAIN_WHITE_CLAMP_CONTROL               0x4888
#define TVW_NTSC_BURST_LEVEL_CONTROL                    0x488c
#define TVW_NTSC_MIN_MAX_GAIN                           0x4890
#define TVW_NTSC_GAIN                                   0x4894
#define TVW_NTSC_PEAK_WHITE_TARGET                      0x4898
#define TVW_NTSC_MIN_PEAK_WHITE_TARGET                  0x489c
#define TVW_NTSC_MAX_PEAK_WHITE_TARGET                  0x48a0
#define TVW_NTSC_CLAMP_LOW_PASS_ALPHA                   0x48a4
#define TVW_NTSC_THRESHOLD_LOW_PASS_ALPHA               0x48a8
#define TVW_NTSC_SYNC_LOW_PASS_ALPHA                    0x48ac
#define TVW_NTSC_BURST_LOW_PASS_ALPHA                   0x48b0
#define TVW_NTSC_MIN_SIGNAL_LOW_PASS_ALPHA              0x48b4
#define TVW_NTSC_CLAMP_AVG                              0x48b8
#define TVW_NTSC_SYNC_LEVEL_AVG                         0x48bc
#define TVW_NTSC_BURST_LEVEL_AVG                        0x48c0
#define TVW_NTSC_GAIN_LOOP_K1_K2                        0x48c4
#define TVW_NTSC_GAIN_LOOP_VERTICAL_K1_K2               0x48c8
#define TVW_NTSC_GAIN_LOOP_VERTICAL_1_9_K1_K2           0x48cc
#define TVW_NTSC_PEAK_WHITE_LOOP_K1_K2                  0x48d0
#define TVW_NTSC_FEEDBACK_TIMING_ADJUST                 0x48e0
#define TVW_NTSC_BIGGEST_SYNC_LEVEL_JUMP                0x48e4
#define TVW_NTSC_BIGGEST_BURST_LEVEL_JUMP               0x48e8
#define TVW_NTSC_MIN_SIGNAL_IN_FRAME                    0x48ec
#define TVW_NTSC_MAX_SIGNAL_IN_FRAME                    0x48f0
#define TVW_NTSC_TESTMUX_MODE                           0x48f4
#define TVW_NTSC_SYNC_LEVEL_DETECT_CTL                  0x48f8
#define TVW_NTSC_HLINE_CTL                              0x48fc
#define TVW_NTSC_VERT_DETECT_CTL                        0x4900
#define TVW_NTSC_AM_LINES                               0x4904
#define TVW_NTSC_SECAM_OFFSET                           0x4908
#define TVW_NTSC_VSTATE_CTL                             0x490c
#define TVW_NTSC_VSTATE_LOCK_CTL                        0x4910
#define TVW_NTSC_LINE_LENGTH_CNT                        0x4914
#define TVW_NTSC_LINE_PER_FRAME                         0x4918
#define TVW_NTSC_SERRATION_CTL                          0x491c
#define TVW_NTSC_EQ_END_LINE                            0x4920
#define TVW_NTSC_VISIBLE_LINE                           0x4924
#define TVW_NTSC_PEAK_WHITE_ONEOVER                     0x4928
#define TVW_NTSC_PEAK_WHITE_LINE_FIELD                  0x492c
#define TVW_NTSC_HALF_LINE_CNT_TIMING                   0x4930
#define TVW_NTSC_LINE_COUNT                             0x4934
#define TVW_NTSC_LINE_CNT_BLANK                         0x4938
#define TVW_NTSC_AM_PERIOD_LEVEL                        0x493c
#define TVW_NTSC_FREE_HALF_LINE_CNT_AVG                 0x4940
#define TVW_NTSC_VSYNC_START_LINE                       0x4944
#define TVW_NTSC_VSYNC_END_LINE                         0x4948
#define TVW_NTSC_VSYNC_START_PIXEL                      0x494c
#define TVW_NTSC_VSYNC_END_PIXEL                        0x4950
#define TVW_NTSC_DEROT_DELTA_THETA_RANGE                0x4954
#define TVW_NTSC_DEROT_FREQ_OFFSET                      0x4958
#define TVW_NTSC_DEROT_FREQ_OFFSET_MIN                  0x495c
#define TVW_NTSC_DEROT_FREQ_OFFSET_MAX                  0x4960
#define TVW_NTSC_FTL_SYNC_LEVEL                         0x4964
#define TVW_NTSC_MANUAL_BAGC_GAIN                       0x4968
#define TVW_NTSC_FIELD_ID_LINE_CNT                      0x496c
#define TVW_ADEC_CONTROL                                0x5000
#define TVW_ADEC_MIXER1_DTO                             0x5004
#define TVW_ADEC_MIXER2_DTO                             0x5008
#define TVW_ADEC_FIR1_COEFF                             0x500c
#define TVW_ADEC_FIR1_CONTROL                           0x5010
#define TVW_ADEC_DEMOD1_CONTROL                         0x5014
#define TVW_ADEC_MIXER3_DTO1                            0x5018
#define TVW_ADEC_MIXER3_DTO2                            0x501c
#define TVW_ADEC_MIXER3_DTO3                            0x5020
#define TVW_ADEC_PILOT_CHANNEL                          0x5024
#define TVW_ADEC_SAP_CHANNEL                            0x5028
#define TVW_ADEC_POWER_LPF1                             0x502c
#define TVW_ADEC_POWER_LPF2                             0x5030
#define TVW_ADEC_SC1_POWER_MEASURE                      0x5034
#define TVW_ADEC_SC1_POWER_THRD_HIGH                    0x5038
#define TVW_ADEC_SC1_POWER_THRD_LOW                     0x503c
#define TVW_ADEC_SC2_POWER_MEASURE                      0x5040
#define TVW_ADEC_SC2_POWER_THRD_HIGH                    0x5044
#define TVW_ADEC_SC2_POWER_THRD_LOW                     0x5048
#define TVW_ADEC_PILOT_POWER_MEASURE                    0x504c
#define TVW_ADEC_PILOT_POWER_THRD_HIGH                  0x5050
#define TVW_ADEC_PILOT_POWER_THRD_LOW                   0x5054
#define TVW_ADEC_SAP_POWER_MEASURE                      0x5058
#define TVW_ADEC_SAP_POWER_THRD_HIGH                    0x505c
#define TVW_ADEC_SAP_POWER_THRD_LOW                     0x5060
#define TVW_ADEC_DECIMATOR_BYPASS_CONTROL               0x5064
#define TVW_ADEC_FIR2_CONTROL                           0x5068
#define TVW_ADEC_DEMOD2_CONTROL                         0x506c
#define TVW_ADEC_UPSAMPLER_GAIN                         0x5070
#define TVW_ADEC_EXPANDER_WIDEBAND_GAIN                 0x5074
#define TVW_ADEC_EXPANDER_SPECTRAL_GAIN                 0x5078
#define TVW_ADEC_MATRIX_CONTROL                         0x507c
#define TVW_ADEC_AVC_LPF                                0x5080
#define TVW_ADEC_AVC_THRESHOLD                          0x5084
#define TVW_ADEC_NOTCH_ZERO                             0x5088
#define TVW_ADEC_NOTCH_POLE                             0x508c
#define TVW_ADEC_RAMPING_TARGET_VOLUME                  0x5090
#define TVW_ADEC_RAMPING_PERIOD                         0x5094
#define TVW_ADEC_UPDATENCO_NCO                          0x5098
#define TVW_ADEC_UPDATENCO_ACQUIRE_LPF                  0x509c
#define TVW_ADEC_UPDATENCO_TRACKING_LPF                 0x50a0
#define TVW_ADEC_UPDATENCO_FIFO_K1                      0x50a4
#define TVW_ADEC_UPDATENCO_FIFO_K2                      0x50a8
#define TVW_ADEC_UPDATENCO_THROTTLE_FACTOR              0x50ac
#define TVW_ADEC_UPDATENCO_THROTTLE_THRD                0x50b0
#define TVW_ADEC_FIFO_STATUS                            0x50b4
#define TVW_ADEC_FIFO_OVERFLOW_CNTR                     0x50b8
#define TVW_ADEC_FIFO_UNDERFLOW_CNTR                    0x50bc
#define TVW_ADEC_I2S_WS_OFFSET                          0x50c0
#define TVW_ADEC_I2S_CONTROL                            0x50c4
#define TVW_ADEC_DECODER_DIAG                           0x50c8
#define TVW_ADEC_DECODER_DIAG_DATA                      0x50d0
#define TVW_ADEC_DECODER_CONTROL                        0x50d4
#define TVW_ADEC_TEST_MUX_SELECT                        0x50d8
#define TVW_ADEC_NICAM_ERROR_THRESHOLD                  0x50dc
#define TVW_ADEC_NICAM_ERROR_CNTR                       0x50e0
#define TVW_ADEC_NICAM_NCO                              0x50e4
#define TVW_ADEC_NICAM_COEFF_DQPSK_RESAMPL              0x50e8
#define TVW_ADEC_NICAM_COEFF_DQPSK_LPF                  0x50ec
#define TVW_ADEC_DC_OFFSET                              0x50f0
#define TVW_ADEC_TESTMUX_DATA                           0x50f4
#define TVW_CPU_CONTROL                                 0x6000
#define TVW_CPU_DEBUG_SEL                               0x6004
#define TVW_CPU_COMB_CONTROL                            0x6008
#define TVW_CPU_FORCE_NOISE                             0x600c
#define TVW_CPU_BURST_PHASE                             0x6010
#define TVW_CPU_HUE                                     0x6014
#define TVW_CPU_PAL_MOD                                 0x6018
#define TVW_IN_PHASE_LEVEL                              0x601c
#define TVW_OUT_PHASE_LEVEL                             0x6020
#define TVW_CPU_MATRIX                                  0x6024
#define TVW_CPU_AVERAGE                                 0x6028
#define TVW_CPU_HALF_BAND                               0x602c
#define TVW_W1_2                                        0x6030
#define TVW_W3_4                                        0x6034
#define TVW_W5_6                                        0x6038
#define TVW_W7_8                                        0x603c
#define TVW_W9_10                                       0x6040
#define TVW_W11                                         0x6044
#define TVW_FRAME_ATI                                   0x6048
#define TVW_YC_CONTROL                                  0x604c
#define TVW_YC_DB1                                      0x6050
#define TVW_NM_DB1_2                                    0x6054
#define TVW_CKILL_DB1_2                                 0x6058
#define TVW_CKILL_DB3_4                                 0x605c
#define TVW_CKILL_1_2                                   0x6060
#define TVW_CKILL_3_4                                   0x6064
#define TVW_CKILL_5_6                                   0x6068
#define TVW_CKILL_7_8                                   0x606c
#define TVW_CKILL_9_10                                  0x6070
#define TVW_CKILL_11_12                                 0x6074
#define TVW_CKILL_13_14                                 0x6078
#define TVW_CKILL_6_7_A                                 0x607c
#define TVW_BURST_DB1_2                                 0x6080
#define TVW_BURST_DB3                                   0x6084
#define TVW_PWM0_CLAMP_GAIN                             0x6088
#define TVW_PWM0_CLAMP_CTRL                             0x608c
#define TVW_PWM1_CLAMP_GAIN                             0x6090
#define TVW_PWM1_CLAMP_CTRL                             0x6094
#define TVW_PWM2_CLAMP_GAIN                             0x6098
#define TVW_PWM2_CLAMP_CTRL                             0x609c
#define TVW_PWM3_CLAMP_GAIN                             0x60a0
#define TVW_PWM3_CLAMP_CTRL                             0x60a4
#define TVW_FWD_CLAMP_DB1                               0x60a8
#define TVW_FWD_CLAMP_DB2                               0x60ac
#define TVW_FWD_CLAMP_DB3                               0x60b0
#define TVW_AGC_DB1_2                                   0x60b4
#define TVW_AGC_DB3_4                                   0x60b8
#define TVW_AGC_DB5_6                                   0x60bc
#define TVW_AGC_DB7                                     0x60c0
#define TVW_TBC_MODE                                    0x60c4
#define TVW_TBC_HOR_OFFSET                              0x60c8
#define TVW_TBC_LUMA_GAIN                               0x60cc
#define TVW_TBC_LUMA_OFFSET                             0x60d0
#define TVW_RY_GAIN                                     0x60d4
#define TVW_RY_OFFSET                                   0x60d8
#define TVW_BY_GAIN                                     0x60dc
#define TVW_BY_OFFSET                                   0x60e0
#define TVW_TBC_D1_OFFSET                               0x60e4
#define TVW_TBC_X1_2                                    0x60e8
#define TVW_TBC_X3_4                                    0x60ec
#define TVW_TBC_X5_6                                    0x60f0
#define TVW_TBC_X7_8                                    0x60f4
#define TVW_TBC_X9_10                                   0x60f8
#define TVW_CPU_DB_3D1_2                                0x60fc
#define TVW_CPU_DB_3D3_4                                0x6100
#define TVW_CPU_DB_3D5_6                                0x6104
#define TVW_CPU_DB_3D7_8                                0x6108
#define TVW_CPU_DB_3D9                                  0x610c
#define TVW_TBC_LOOP_BACK                               0x6110
#define TVW_TBC_LOOP_ACCUM                              0x6114
#define TVW_PSEUDO_SYNC_WIN                             0x6118
#define TVW_PSEUDO_SYNC_CTRL                            0x611c
#define TVW_PSEUDO_SYNC_WIDTH_DET                       0x6120
#define TVW_MV_COLORSTRIPE_LINE                         0x6124
#define TVW_MV_COLORSTRIPE_BURST                        0x6128
#define TVW_MV_COLORSTRIPE_THRESH                       0x612c
#define TVW_MV_COLOR_STRIP                              0x6130
#define TVW_PSEUDO_SYNC_STATUS                          0x6134
#define TVW_SYNC_STRIP_BP_CLAMP                         0x6138
#define TVW_SYNC_STRIP_MIN_SYNC_RECURSE                 0x613c
#define TVW_SYNC_STRIP_SLICE_POINT                      0x6140
#define TVW_SYNC_STRIP_TP_CTRL                          0x6144
#define TVW_SYNC_STRIP_V_DETECT_1_2                     0x6148
#define TVW_SYNC_STRIP_V_DETECT_3_4                     0x614c
#define TVW_SYNC_STRIP_V_DETECT_5_6                     0x6150
#define TVW_SYNC_STRIP_V_DETECT_7_8                     0x6154
#define TVW_SYNC_STRIP_V_DETECT_9                       0x6158
#define TVW_BACK_PORCH                                  0x615c
#define TVW_RESAMP_CONTROL                              0x6160
#define TVW_RESAMP_YOUT_SHFT                            0x6164
#define TVW_RESAMP_YOUT_SCALE                           0x6168
#define TVW_RESAMP_COUT_SHFT                            0x616c
#define TVW_RESAMP_COUT_SCALE                           0x6170
#define TVW_RESAMP0_CLAMP_CONTROL                       0x6174
#define TVW_RESAMP1_CLAMP_CONTROL                       0x6178
#define TVW_RESAMP_INITPHASEOFFSET                      0x617c
#define TVW_RESAMP_NCORATE_HIGH                         0x6180
#define TVW_RESAMP_NCORATE_MID                          0x6184
#define TVW_RESAMP_NCORATE_LOW                          0x6188
#define TVW_RESAMP_PHASE_ERROR_CONTROL                  0x618c
#define TVW_RESAMP_PWR_LPF_SCALE                        0x6190
#define TVW_RESAMP_POWER_THRESHOLD_HIGH                 0x6194
#define TVW_RESAMP_POWER_THRESHOLD_LOW                  0x6198
#define TVW_RESAMP_STATUS                               0x619c
#define TVW_PEAK_WHITE_THRESH                           0x61a0
#define TVW_PEAK_WHITE_HWIN                             0x61a4
#define TVW_PEAK_WHITE_VWIN                             0x61a8
#define TVW_PEAK_WHITE_AVERAGE                          0x61ac
#define TVW_PEAK_WHITE                                  0x61b0
#define TVW_MEAN_WHITE                                  0x61b4
#define TVW_DECIMATOR_CONTROL                           0x61b8
#define TVW_D2_COEFF_1_0                                0x61bc
#define TVW_D2_COEFF_3_2                                0x61c0
#define TVW_D2_COEFF_5_4                                0x61c4
#define TVW_D2_COEFF_7_6                                0x61c8
#define TVW_D2_COEFF_9_8                                0x61cc
#define TVW_D2_COEFF_11_10                              0x61d0
#define TVW_D2_COEFF_13_12                              0x61d4
#define TVW_D2_COEFF_15_14                              0x61d8
#define TVW_D2_COEFF_17_16                              0x61dc
#define TVW_D2_COEFF_19_18                              0x61e0
#define TVW_DEBUG_MUX_SEL                               0x61e4
#define TVW_FINAL_DB1_2                                 0x61e8
#define TVW_FINAL_DB3_4                                 0x61ec
#define TVW_FINAL_DB5_6                                 0x61f0
#define TVW_FINAL_DB7_8                                 0x61f4
#define TVW_FINAL_DB9_10                                0x61f8
#define TVW_FINAL_DB11_12                               0x61fc
#define TVW_FINAL_DB13_14                               0x6200
#define TVW_FINAL_DB15_16                               0x6204
#define TVW_FINAL_DB17_18                               0x6208
#define TVW_FINAL_DB19_20                               0x620c
#define TVW_FINAL_DB21_22                               0x6210
#define TVW_FINAL_DB23_24                               0x6214
#define TVW_FINAL_DB25_26                               0x6218
#define TVW_FINAL_DB27                                  0x621c
#define TVW_ACC_CONTROL                                 0x6220
#define TVW_ACC_SPEED                                   0x6224
#define TVW_ACC_TH_ADJ                                  0x6228
#define TVW_ACC_BURST_POS1_2                            0x622c
#define TVW_ACC_BURST_POS3_4                            0x6230
#define TVW_BURST_WIDTH1_2                              0x6234
#define TVW_BURST_WIDTH3_4                              0x6238
#define TVW_BURST_WIDTH5_6                              0x623c
#define TVW_BURST_WIDTH7                                0x6240
#define TVW_SYNC_POS1_2                                 0x6244
#define TVW_SYNC_POS3_4                                 0x6248
#define TVW_SYNC_POS5_6                                 0x624c
#define TVW_SYNC_POS7_8                                 0x6250
#define TVW_SYNC_POS9_10                                0x6254
#define TVW_SYNC_POS11_12                               0x6258
#define TVW_CCR_ADJUST                                  0x625c
#define TVW_NP_CONTROL                                  0x6260
#define TVW_Q_CONTROL                                   0x6264
#define TVW_SECAM_CTRL                                  0x6268
#define TVW_NEG_BP_CTR1_2                               0x626c
#define TVW_NEG_BP_CTR3_4                               0x6270
#define TVW_NEG_BP_CTR4_5                               0x6274
#define TVW_PAL_MOTION_CTRL1_2                          0x6278
#define TVW_MOTION_3D                                   0x627c
#define TVW_SYNC_LOW_DB1_2                              0x6280
#define TVW_SYNC_LOW_DB3_4                              0x6284
#define TVW_SYNC_LOW_DB5                                0x6288
#define TVW_FIELD_RST1                                  0x628c
#define TVW_FV_WIDE1_2                                  0x6290
#define TVW_FV_WIDE3_5                                  0x6294
#define TVW_FV_WIDE5                                    0x6298
#define TVW_SNAP_DB1_2                                  0x629c
#define TVW_SNAP_DB3                                    0x62a0
#define TVW_TEAR_DB1                                    0x62a4
#define TVW_VCR_DB1_2                                   0x62a8
#define TVW_IIR_BW                                      0x62ac
#define TVW_PAUSE_FIX1_2                                0x62b0
#define TVW_PAUSE_FIX3_4                                0x62b4
#define TVW_PAUSE_FIX5_6                                0x62b8
#define TVW_CATV_DB1_2                                  0x62bc
#define TVW_CATV_FIELD                                  0x62c0
#define TVW_SYNC_DETECT_DB1_2                           0x62c4
#define TVW_NM_PROG1_2                                  0x62c8
#define TVW_NM_PROG3_4                                  0x62cc
#define TVW_AFE_AGC_CONTROL                             0x62d0
#define TVW_AGC_CONTROL_2_3                             0x62d4
#define TVW_AGC_CONTROL_4_5                             0x62d8
#define TVW_AGC_CONTROL_6_7                             0x62dc
#define TVW_AGC_ACC_MODE                                0x62e0
#define TVW_COMB_3D_ADJUST                              0x62e4
#define TVW_TBC_BP_ST1_2                                0x62e8
#define TVW_TBC_BP_ST3                                  0x62ec
#define TVW_RISING_PROG1_2                              0x62f0
#define TVW_RISING_PROG3                                0x62f4
#define TVW_YELLOW_DB1_2                                0x62f8
#define TVW_BURST_RISING1_2                             0x62fc
#define TVW_VBI_END_FIELD                               0x6300
#define TVW_CB_PLL_TEST_1_2                             0x6304
#define TVW_CB_PLL_TEST_3_4                             0x6308
#define TVW_CB_PLL_TEST_5_6                             0x630c
#define TVW_CB_PLL_TEST_7_8                             0x6310
#define TVW_CB_PLL_TEST_9_10                            0x6314
#define TVW_CB_PLL_ACC1_2                               0x6318
#define TVW_CB_PLL_ACC3_4                               0x631c
#define TVW_CB_PLL_ACC5_6                               0x6320
#define TVW_CB_PLL_ACC7                                 0x6324
#define TVW_CBPLL_PROG                                  0x6328
#define TVW_CBCR_OFFSET                                 0x632c
#define TVW_VLOCK_ACQUIRE_CTRL                          0x6330
#define TVW_VLOCK_ACQUIRE_FIELD_WIN                     0x6334
#define TVW_VLOCK_ACQUIRE_FIELD_LOCK                    0x6338
#define TVW_VLOCK_ACQUIRE_PAL_FIELD                     0x633c
#define TVW_GENLOCK_FLAG                                0x6340
#define TVW_GENLOCK_VCR                                 0x6344
#define TVW_GENLOCK_REC_SELECT                          0x6348
#define TVW_GENLOCK_TRICK_MODE_1_2                      0x634c
#define TVW_GENLOCK_TRICK_MODE_3_4                      0x6350
#define TVW_GENLOCK_TRICK_MODE_5                        0x6354
#define TVW_GENLOCK_VALID_3D                            0x6358
#define TVW_GENLOCK_CLAMP_GAIN                          0x635c
#define TVW_GENLOCK_BURST_TH                            0x6360
#define TVW_GENLOCK_BURST_GAIN                          0x6364
#define TVW_AGC_FAST_20P                                0x6368
#define TVW_AGC_FAST_HIGH_TH                            0x636c
#define TVW_AGC_FAST_LOW_TH                             0x6370
#define TVW_AGC_FAST_PEAK_BLACK_TH                      0x6374
#define TVW_AGC_FAST_SPEED_0_1                          0x6378
#define TVW_AGC_FAST_SPEED_2_3                          0x637c
#define TVW_HLOCK_ACQUIRE_LOW_BP_CONTROL                0x6380
#define TVW_HLOCK_ACQUIRE_LOW_EDGE                      0x6384
#define TVW_HLOCK_ACQUIRE_LOW_FOUND                     0x6388
#define TVW_HLOCK_ACQUIRE_LOW_LL_WIN                    0x638c
#define TVW_HLOCK_ACQUIRE_LOW_LOST                      0x6390
#define TVW_HLOCK_ACQUIRE_REC_LOST                      0x6394
#define TVW_HLOCK_ACQUIRE_FOUND                         0x6398
#define TVW_HLOCK_ACQUIRE_REC_EDGE                      0x639c
#define TVW_HLOCK_ACQUIRE_REC_LL                        0x63a0
#define TVW_HLOCK_ACQUIRE_SYNC_SEL                      0x63a4
#define TVW_HLOCK_ACQUIRE_SYNC_LOW_TH                   0x63a8
#define TVW_HLOCK_ACQUIRE_SYNC_REC_TH                   0x63ac
#define TVW_MEASURE_SYNCTIP_SYNC_REC_CONTROL            0x63b0
#define TVW_MEASURE_SYNCTIP_TH0                         0x63b4
#define TVW_MEASURE_SYNCTIP_TH1                         0x63b8
#define TVW_MEASURE_SYNCTIP_BP_LP                       0x63bc
#define TVW_FRAME_SEN_CTRL                              0x63c0
#define TVW_NEW_COMB_CTRL                               0x63c4
#define TVW_BURST_AMP                                   0x63c8
#define TVW_GAIN_AGC                                    0x63cc
#define TVW_VIDEO_TIMING                                0x63d0
#define TVW_LINE_COUNT1                                 0x63d4
#define TVW_LINE_COUNT2                                 0x63d8
#define TVW_LINE_COUNT3                                 0x63dc
#define TVW_LINE_COUNT4                                 0x63e0
#define TVW_DEBUG_READ                                  0x63e4
#define TVW_LAST_TBC_DB1_2                              0x63e8
#define TVW_LAST_TBC_DB3_4                              0x63ec
#define TVW_LAST_TBC_DB5_6                              0x63f0
#define TVW_LAST_TBC_DB7                                0x63f4
#define TVW_VBI_ADDR                                    0x63f8
#define TVW_VBI_RD_DATA                                 0x63fc
#define TVW_VBI_WR_DATA                                 0x63fc
#define TVW_VDEC_MEM_EN                                 0x6400
#define TVW_DEBUG_CONV_1_2                              0x6404
#define TVW_DEBUG_CONV_3_4                              0x6408
#define TVW_DEBUG_CONV_5                                0x640c
#define TVW_CONTROL_1D1_2                               0x6410
#define TVW_CONTROL_1D3_4                               0x6414
#define TVW_CONTROL_TWO                                 0x6418
#define TVW_OFFSET_CALC_STATUS                          0x641c
#define TVW_OFFSET_CALC_LOG                             0x6420
#define TVW_OFFSET_CALC_COUNT                           0x6424
#define TVW_OFFSET_CALC_SCH_VALUE                       0x6428
#define TVW_IF_COEF1                                    0x642c
#define TVW_IF_COEF2                                    0x6430
#define TVW_IF_COEF3                                    0x6434
#define TVW_AFE_DEBUG_AGC                               0x6438
#define TVW_VDEC_STATUS                                 0x643c
#define TVW_VDEC_SYNC_LEVEL                             0x6440
#define TVW_VDEC_CLAMP_OUT                              0x6444
#define TVW_VDEC_LOW_HLOCK_FLAG                         0x6448
#define TVW_VDEC_LOW_LINE_MEAS                          0x644c
#define TVW_VDEC_REC_HLOCK_FLAG                         0x6450
#define TVW_VDEC_REC_LINE_MEAS                          0x6454
#define TVW_VDEC_HLOCK_FLAG                             0x6458
#define TVW_VDEC_FIELD_LENGTH                           0x645c
#define TVW_VDEC_VIDEO_FLAGS                            0x6460
#define TVW_CB_PLL_ACCUM                                0x6464
#define TVW_CB_PLL_FLAG                                 0x6468
#define TVW_CP_CTRL                                     0x646c
#define TVW_MEASURED_NOISE                              0x6470
#define TVW_NON_STANDARD_FLAG1                          0x6474
#define TVW_NON_STANDARD_FLAG2                          0x6478
#define TVW_NON_STANDARD_FLAG3                          0x647c
#define TVW_NON_STANDARD_FLAG4                          0x6480
#define TVW_BP_LEVEL                                    0x6484
#define TVW_NEW_AGC_GAIN                                0x6488
#define TVW_ACC_GAIN                                    0x648c
#define TVW_DEMOD_IIR                                   0x6490
#define TVW_ABS_SQ_BURST_IIR                            0x6494
#define TVW_FIELD_V_POS                                 0x6498
#define TVW_RESAMP0_DEBUG                               0x649c
#define TVW_CLAMP_DEBUG                                 0x64a0
#define TVW_VFLIP_PROG                                  0x64a4
#define TVW_PAL_VFLIP_TH1_2                             0x64a8
#define TVW_PAL_VFLIP_TH3_4                             0x64ac
#define TVW_VFLIP_MAX1_2                                0x64b0
#define TVW_VFLIP_MAX3_4                                0x64b4
#define TVW_VFLIP_MAX5_6                                0x64b8
#define TVW_VFLIP_CK_SNAP                               0x64bc
#define TVW_STANDARD_CONTROL1_2                         0x64c0
#define TVW_AUTO_SM1                                    0x64c4
#define TVW_AUTO_VFLIP1_2                               0x64c8
#define TVW_AUTO_VFLIP3_4                               0x64cc
#define TVW_AUTO_VFLIP5_6                               0x64d0
#define TVW_SCART_CTRL                                  0x64d4
#define TVW_AUTO_READ1                                  0x64d8
#define TVW_VFLIP1_2_ON                                 0x64dc
#define TVW_CBPLL_ABS                                   0x64e0
#define TVW_LPF_LL                                      0x64e4
#define TVW_SHARPNESS_CONTROL                           0x64e8
#define TVW_SHARPNESS_FILTER_VSTART                     0x64ec
#define TVW_DEBUG_OUT                                   0x64f0
#define TVW_FPLL_DBG_PORT                               0x64f4
#define TVW_NOISE_MEASURE_CONTROL                       0x64f8
#define TVW_NOISE_MEASURE_VCOUNT_WINDOW                 0x64fc
#define TVW_MEMORY_MARGIN_CTL0                          0x6500
#define TVW_MEMORY_MARGIN_CTL1                          0x6504
#define TVW_FSC_PROG1_2                                 0x6508
#define TVW_FSC_PROG3_4                                 0x6510
#define TVW_VSYNC_SLICE1_4                              0x6514
#define TVW_ABS_SQ_BURST_IIR_N_EN                       0x6518
#define TVW_ABS_SQ_BURST_IIR_P_EP                       0x651c
#define TVW_VDEC_FIFO_CTL                               0x6520
#define TVW_VDEC_INTERRUPT_ENABLE                       0x6524
#define TVW_VDEC_INTERRUPT_CLEAR                        0x6528
#define TVW_VDEC_INTERRUPT_STATUS                       0x6528
#define TVW_VDEC_LOCK_INTR_CTRL                         0x652c
#define TVW_VDEC_MV_INTR_CTRL                           0x6530
#define TVW_VDEC_TRICK_MODE_INTR_CTRL                   0x6534
#define TVW_VDEC_STD_INTR_CTRL                          0x6538
#define TVW_VDEC_NOISE_MEASURE_HIGH_INTR_CTRL           0x653c
#define TVW_VDEC_NOISE_MEASURE_LOW_INTR_CTRL            0x6540
#define TVW_VDEC_NOISE_INTR_TRIGGER                     0x6544
#define TVW_VDEC_VSYNC_INTR_CTRL                        0x6548
#define TVW_VDEC_FIELD_ID_INTR_CTRL                     0x654c
#define TVW_VDEC_DEBUG1_INTR_CTRL                       0x6550
#define TVW_VDEC_MD_CTRL                                0x6554
#define TVW_MOTION_1D_2D                                0x6558
#define TVW_TRICK_AUTO_STANDARD1_2                      0x655c
#define TVW_VSYNC_SLICE3                                0x6560
#define TVW_SAME_CH_3D1_2                               0x6564
#define TVW_SECAM_SEP_DB0                               0x6570
#define TVW_SECAM_SEP_DB1                               0x6574
#define TVW_SECAM_SEP_DB2                               0x6578
#define TVW_SECAM_SEP_DB3                               0x657c
#define TVW_SECAM_SEP_DB4                               0x6580
#define TVW_SECAM_SEP_DB5                               0x6584
#define TVW_SECAM_SEP_DB6                               0x6588
#define TVW_SECAM_SEP_DB7                               0x658c
#define TVW_SECAM_SEP_DB8                               0x6590
#define TVW_SECAM_SEP_DB9                               0x6594
#define TVW_SECAM_SEP_DB10                              0x6598
#define TVW_SECAM_SEP_DB11                              0x659c
#define TVW_SECAM_SEP_DB12                              0x65a0
#define TVW_SECAM_SEP_DB13                              0x65a4
#define TVW_SECAM_SEP_DB14                              0x65a8
#define TVW_SECAM_SEP_DB15                              0x65ac
#define TVW_SECAM_SEP_DB16                              0x65b0
#define TVW_SECAM_SEP_DR0                               0x65b4
#define TVW_SECAM_SEP_DR1                               0x65b8
#define TVW_SECAM_SEP_DR2                               0x65bc
#define TVW_SECAM_SEP_DR3                               0x65c0
#define TVW_SECAM_SEP_DR4                               0x65c4
#define TVW_SECAM_SEP_DR5                               0x65c8
#define TVW_SECAM_SEP_DR6                               0x65cc
#define TVW_SECAM_SEP_DR7                               0x65d0
#define TVW_SECAM_SEP_DR8                               0x65d4
#define TVW_SECAM_SEP_DR9                               0x65d8
#define TVW_SECAM_SEP_DR10                              0x65dc
#define TVW_SECAM_SEP_DR11                              0x65e0
#define TVW_SECAM_SEP_DR12                              0x65e4
#define TVW_SECAM_SEP_DR13                              0x65e8
#define TVW_SECAM_SEP_DR14                              0x65ec
#define TVW_SECAM_SEP_DR15                              0x65f0
#define TVW_SECAM_SEP_DR16                              0x65f4
#define TVW_SECAM_CLAMP_CTRL0                           0x65fc
#define TVW_SECAM_CLAMP_CTRL1                           0x6600
#define TVW_SECAM_CLAMP_CTRL2                           0x6604
#define TVW_SECAM_AGC_CTRL0                             0x6608
#define TVW_SECAM_AGC_CTRL1                             0x660c
#define TVW_SECAM_AGC_CTRL2                             0x6610
#define TVW_SECAM_AGC_CTRL3                             0x6614
#define TVW_SECAM_CTRL0                                 0x6618
#define TVW_SECAM_CTRL1                                 0x661c
#define TVW_SECAM_CTRL2                                 0x6620
#define TVW_SECAM_BURST                                 0x6624
#define TVW_SECAM_AGC                                   0x6628
#define TVW_SECAM_DEV                                   0x662c
#define TVW_SECAM_DIAG                                  0x6630
#define TVW_SECAM_DELAY                                 0x6634
#define TVW_SECAM_BURST2                                0x6638
#define TVW_SECAM_CLAMP_CTRL3                           0x663c
#define TVW_SECAM_DEEMPHASIS_COEFF                      0x6640
#define TVW_SECAM_SEPARATION_CNTRL                      0x6644
#define TVW_SECAM_EMPHASIS_BOOST                        0x6648
#define TVW_SECAM_DIAG_DATA                             0x664c
#define TVW_SECAM_CLAMP_CTRL4                           0x6650
#define TVW_SECAM_AGC_CTRL4                             0x6654
#define TVW_SECAM_SEPARATION_CTRL1                      0x6658
#define TVW_SECAM_CONTROL                               0x665c
#define TVW_SECAM_CLOCHE_COEFB0                         0x6660
#define TVW_SECAM_CLOCHE_COEFB1                         0x6664
#define TVW_SECAM_CLOCHE_COEFA1                         0x6668
#define TVW_SECAM_NOISE_SCALING_THRESH_LOW              0x666c
#define TVW_SECAM_NOISE_SCALING_SLOPE                   0x6670
#define TVW_SECAM_NOISE_MEASURE_CONTROL                 0x6674
#define TVW_SECAM_NOISE_MEASURE_VCOUNT_WINDOW           0x6678
#define TVW_SECAM_NOISE_MEASUREMENT                     0x667c
#define TVW_SECAM_CARRIER_AMP_CTRL                      0x6680
#define TVW_SECAM_CARRIER_AMP_CTRL1                     0x6684
#define TVW_SECAM_CARRIER_AMP_CTRL2                     0x6688
#define TVW_SECAM_NARROW_TRAP0                          0x668c
#define TVW_SECAM_NARROW_TRAP1                          0x6690
#define TVW_SECAM_NARROW_TRAP2                          0x6694
#define TVW_SECAM_NARROW_TRAP3                          0x6698
#define TVW_SECAM_NARROW_TRAP4                          0x669c
#define TVW_SECAM_NARROW_TRAP5                          0x66a0
#define TVW_SECAM_NARROW_TRAP6                          0x66a4
#define TVW_SECAM_NARROW_TRAP7                          0x66a8
#define TVW_SECAM_NARROW_TRAP8                          0x66ac
#define TVW_SECAM_NARROW_TRAP9                          0x66b0
#define TVW_SECAM_NARROW_TRAP10                         0x66b4
#define TVW_SECAM_NARROW_TRAP11                         0x66b8
#define TVW_SECAM_NARROW_TRAP12                         0x66bc
#define TVW_SECAM_NARROW_TRAP13                         0x66c0
#define TVW_SECAM_NARROW_TRAP14                         0x66c4
#define TVW_SECAM_NARROW_TRAP15                         0x66c8
#define TVW_SECAM_NARROW_TRAP16                         0x66cc
#define TVW_SECAM_CONTROL3                              0x66d0
#define TVW_SECAM_CONTROL5                              0x66d4
#define TVW_TBC_SM_CTRL                                 0x66e0
#define TVW_TBC_SM_VBI_WIND_START                       0x66e4
#define TVW_TBC_SM_H_WIND_START                         0x66e8
#define TVW_TBC_SM_VSYNC_MAX_LINE_COUNT                 0x66ec
#define TVW_TBC_SM_VSYNC_MIN_LINE_COUNT                 0x66f0
#define TVW_TBC_SM_VBI_V_START                          0x66f4
#define TVW_TBC_SM_VBI_V_END                            0x66f8
#define TVW_TBC_STATUS                                  0x66fc
#define TVW_VPLL_DBG_PORT                               0x6700
#define TVW_TBC_Y_DELAY                                 0x6704
#define TVW_TBC_CBCR_DELAY                              0x6708
#define TVW_TBC_OFFSET_SKEW                             0x670c
#define TVW_TBC_PAUSE                                   0x6710
#define TVW_TBC_PLL_OVER_GAIN                           0x6714
#define TVW_TBC_LINE_BUF_FREQ_DIF                       0x6718
#define TVW_TBC_LINE_BUF_READ_DISTANCE                  0x671c
#define TVW_TBC_LINE_BUF_READ_ACCUMF                    0x6720
#define TVW_TBC_FAST_FH1_2                              0x6724
#define TVW_TBC_FAST_FH3                                0x6728
#define TVW_TBC_CCR1_2_CONTROL                          0x672c
#define TVW_TBC_CCR3_CONTROL                            0x6730
#define TVW_TBC_SKEW_ENABLE2                            0x6734
#define TVW_TBC_SKEW_ENABLE3_4                          0x6738
#define TVW_TBC_TRI_EDGE1_2                             0x673c
#define TVW_TBC_TRI_EDGE3_4                             0x6740
#define TVW_TBC_TRI_EDGE5                               0x6744
#define TVW_TBC_TRI_EDGE_DEL1_2                         0x6748
#define TVW_TBC_HSYNC_PLL_CTRL                          0x674c
#define TVW_TBC_HSYNC_WINDOW                            0x6750
#define TVW_TBC_HSYNC_SUBCNT_OFFSET                     0x6754
#define TVW_RISE_TBC_DB1_2                              0x6758
#define TVW_RISE_TBC_DB3                                0x675c
#define TVW_BLUE_SCREEN_CTRL                            0x6760
#define TVW_BLUE_SCREEN_LOCK_THRESHOLD                  0x6764
#define TVW_BLUE_SCREEN_Y_CB_CR                         0x6768
#define TVW_SECART_CTRL                                 0x676c
#define TVW_HUE_DEGREE                                  0x6770
#define TVW_HUE_COS_CB_HUE_SIN_CR                       0x6774
#define TVW_HUE_SIN_CB_HUE_COS_CR                       0x6778
#define TVW_QM_CONTROL                                  0x6780
#define TVW_QM_F1_BASE_ADDR                             0x6790
#define TVW_QM_F2_BASE_ADDR                             0x6794
#define TVW_MD_CONTROL                                  0x6798
#define TVW_MD_BASE                                     0x679c
#define TVW_SCART_RGB_CONTROL                           0x67a0
#define TVW_SCART_DELAY_1                               0x67a4
#define TVW_SCART_DELAY_2                               0x67a8
#define TVW_SCART_R_Clamp_Ctrl                          0x67ac
#define TVW_SCART_R_Clamp_Window                        0x67b0
#define TVW_SCART_G_Clamp_Ctrl                          0x67b4
#define TVW_SCART_G_Clamp_Window                        0x67b8
#define TVW_SCART_B_Clamp_Ctrl                          0x67bc
#define TVW_SCART_B_Clamp_Window                        0x67c0
#define TVW_SCART_R_AGC_SHIFT                           0x67c4
#define TVW_SCART_R_AGC_GAIN                            0x67c8
#define TVW_SCART_G_AGC_SHIFT                           0x67cc
#define TVW_SCART_G_AGC_GAIN                            0x67d0
#define TVW_SCART_B_AGC_SHIFT                           0x67d4
#define TVW_SCART_B_AGC_GAIN                            0x67d8
#define TVW_SCART_RGB_AGC_CTRL                          0x67dc
#define TVW_SCART_RGB_AGC_SYNC                          0x67e0
#define TVW_SCART_RGB_AGC_WINDOW                        0x67e4
#define TVW_SCART_RGB_AGC_PEAK                          0x67e8
#define TVW_SCART_RGB_AGC_PEAK_CTRL1                    0x67ec
#define TVW_SCART_RGB_AGC_PEAK_CTRL2                    0x67f0
#define TVW_SCART_RGB_AGC_PEAK_CTRL3                    0x67f4
#define TVW_SCART_RGB_AGC_GAIN_LIMIT                    0x67f8
#define TVW_SCART_RGB_CC_Y_shift                        0x67fc
#define TVW_SCART_RGB_CC_UV_shift                       0x6800
#define TVW_SCART_RGB_CC_R_2_Y                          0x6804
#define TVW_SCART_RGB_CC_GB_2_Y                         0x6808
#define TVW_SCART_RGB_CC_R_2_U                          0x680c
#define TVW_SCART_RGB_CC_GB_2_U                         0x6810
#define TVW_SCART_RGB_CC_R_2_V                          0x6814
#define TVW_SCART_RGB_CC_GB_2_V                         0x6818
#define TVW_SCART_EDGE_SHAPER_COEFF_0_2                 0x681c
#define TVW_SCART_EDGE_SHAPER_COEFF_3_5                 0x6820
#define TVW_SCART_EDGE_SHAPER_COEFF_6_8                 0x6824
#define TVW_SCART_EDGE_SHAPER_COEFF_9_10                0x6828
#define TVW_SCART_PRESENT                               0x682c
#define TVW_SCART_BLENDER_CTRL                          0x6830
#define TVW_SCART_BLENDER_FB_THRESHOLD                  0x6834
#define TVW_SCART_DIAG                                  0x6838
#define TVW_SCART_DIAG_DATA                             0x683c
#define TVW_SCART_BLENDER_FB_DETECT1                    0x6840
#define TVW_SCART_BLENDER_FB_DETECT2                    0x6844
#define TVW_SCART_BLENDER_FB_DETECT3                    0x6848
#define TVW_SCART_MISC_CONTROL                          0x684c
#define TVW_SCART_FB_CTRL                               0x6850

#endif
